### ISSUE TITLE
Wallet Logic

### ISSUE THREAD

**Issue by shkfnly** [CirclesUBI/circles-mobile#19]
When adding a new wallet the wallet selection dropdown doesn't correctly update.

**Comment by ronitronitronit** [comment]
It works for me, or maybe I'm not understanding this issue correctly. When the user adds a new org wallet, they end up in the org wallet screen. When they leave that, they are led to the org home screen of that particular org. The drop-down code specifies that the org that the user is currently in NOT be shown in the drop down. Do you want it to be shown instead?

Or maybe I just don't get the issue - could you clarify? Thanks :D @shkfnly

**Comment by ronitronitronit** [comment]
I don't think it's just the wallet selection dropdown that isn't updating correctly - when the user starts on their main wallet (not an org wallet) start page and then creates a new org wallet from there, they are brought back to the start page of their main wallet after completing the creation of the new one. But when the user is on an existing org wallet start page, and then creates a new org wallet from there, they are brought to the start page of that newly created org wallet upon completion (as it should be, I'm guessing?)....looking into it.

**Comment by ronitronitronit** [comment]
Ok, think I fixed it but it's not the best solution. On line 76 of components/OrgWallet/OrgWalletScreen the X button was navigating the user to simply "goBack" - but if they came from their base wallet, then "back" would be the primary home screen, not the org home screen. This would explain why this doesn't happen when they started off from an org home screen in the first place(?). So I changed "goBack" to navigate.("OrgHome"), and now they are sent to the home screen of that org and the dropdown reflects that. Double check it to see if it's sound. But if it is, not sure it's the best solution anyway - why not have one home screen that renders differently depending on if the props send a primary or org wallet rather than having an org home screen and a primary home screen?

**Comment by ronitronitronit** [comment]
On line 76 of components/OrgWallet/OrgWalletScreen the X button was navigating the user to simply "goBack" - but if they came from their base wallet, then "back" would be the primary home screen, not the org home screen. This would explain why this doesn't happen when they started off from an org home screen in the first place(?). So I changed "goBack" to navigate.("OrgHome"), and now they are sent to the home screen of that org and the dropdown reflects that. Double check it to see if it's sound. https://github.com/CirclesUBI/circles-mobile/pull/22 @shkfnly

**Comment by edzillion** [comment]
Hmm your thinking seems sound but usually with RN you are using a navigator which acts like a FIFO stack = you can 'push' a new page onto the stack or go back to the last one. You can also wipe the stack and replace the bottom page, for when you want to change the base page (like when you go back to home on an app)

**Comment by ronitronitronit** [comment]
So in this case, the "go back" sends them to the base home (the one holding their ubi wallet), because that's the last thing on the stack, where they came from when they first found the option to create an org wallet. But they don't need to go back, they need to go somewhere they've never been before: the org home, not the base home, because they just made an org wallet and it's going to send those props. If there was one home that rendered differently/rendered different components depending on whether the user was viewing a base wallet or org wallet (this is how I would do it in React but it looks like RN is a lot more compartmentalized - but I know practically nothing about RN), then just "going back" would make sense, but right now the structure is separate. At least that's how I understand it.

Edit: Oh ok I read your last sentence again and if we can replace the bottom page to a different base page, then great, but is it better?

**Comment by edzillion** [comment]
> Edit: Oh ok I read your last sentence again and if we can replace the bottom page to a different base page, then great, but is it better?

Well just think if it like a temporary start position. There are times in apps (like when you are filling out a form over a few pages) where you don't want the user to accidentally back out of a process. Remember that you can always reset the base page to home when the click the home button

**Comment by ronitronitronit** [comment]
> There are times in apps (like when you are filling out a form over a few pages) where you don't want the user to accidentally back out of a process

Makes sense. But this isn't a problem in this case. The back button here sends them to the last step fine.

The issue is that there are two navigators, two home screen containers, and two home screens, one regular and one for org. It's not a actually an issue, it just means that "goBack" will send them back to whichever one they came from when they click the X button from the wallet view. This doesn't make sense when they just created an org and the props that will be sent are org props. They should be sent to the org home screen when they click the X from the wallet, but are instead sent to the regular one. 

So do you want me to look into a different solution that actually changes the base of the stack? It's cool if this solution isn't great, but in any case, the user will ALWAYS need to go back to the org home and not just "go back" - which could either be to the org home or the regular home depending on where they started from.

**Comment by edzillion** [comment]
I see. I think @shkfnly might be able to help here, because I agree with you that in general you want one view for home which changes depending on the model it's fed.

**Comment by ronitronitronit** [comment]
That sounds like a lot of annoying work but maybe it's the noobness in me talking. It functions fine separated so far, no? I could look into actually resetting the base of the stack...it looks like something like this was attempted at some point but as far as I can tell, the code isn't reached (checkout line 65 of components/AddOrgWallet/AddAdmin) or maybe I'm missing how it is?

**Comment by shkfnly** [comment]
Let's leave the two homes separate because they are different layout and structures

**Comment by edzillion** [comment]
fixed, need a better description next time as it was hard to know what I was testing.
